'use strict';
const $=id=>document.getElementById(id),pick=arr=>arr[Math.floor(Math.random()*arr.length)],shuffle=arr=>arr.map(x=>[Math.random(),x]).sort((a,b)=>a[0]-b[0]).map(x=>x[1]);
const colors=['#bc94f4','#62cab6','#e5b476','#ea8dad','#8baff2','#9cc782'];
const starts='lunar mint pixel cozy silent cloud neon solar velvet retro sleepy tiny wild lucky night ocean amber nova soft echo mellow frost cosmic copper lofi golden urban happy olive silver peach violet aqua crystal mocha maple rainy orbit chill indie'.split(' ');
const ends='fox wave bear byte cat owl fern drift bloom spark moth quest comet leaf ghost panda finch raven otter sage tiger rider dream mango bean atlas frog tide pearl groove wisp kiwi tune wolf kite trail lens muse pine haven'.split(' ');
const scenes=[['Auto · follow camera','Just Chatting','✧'],['Just chatting','Just Chatting','☏'],['Late night gaming','Gaming','⌘'],['One more attempt','Challenges','⚑'],['Cooking & food','Food & Drink','♧'],['IRL & outdoors','IRL','❧'],['Music & practice','Music','♫'],['Focus & study','Study With Me','▤']];
const cues=[['☺','Laugh'],['♜','Win'],['↻','Fail'],['☏','Debate'],['☕','BRB'],['▷','Back']];
const usedNames=new Set(),usedThreads=new Set();
const canonical=s=>s.toLowerCase().replace(/’/gu,"'").match(/[\p{L}\p{N}]+/gu)?.join(' ')||'';
const stop=new Set('i a the it is and to for of that this in on my you your we me s t m ve re just really so but with some'.split(' '));
class Memory{constructor(){this.exact=new Set();this.recent=[]}tokens(s){return new Set(canonical(s).split(' ').filter(x=>!stop.has(x)))}allows(s){if(!s||this.exact.has(canonical(s)))return false;const a=this.tokens(s);return !this.recent.some(b=>{if(a.size<3||b.size<3)return false;const n=[...a].filter(x=>b.has(x)).length;return n/new Set([...a,...b]).size>=.64||(Math.min(a.size,b.size)>=4&&n/Math.min(a.size,b.size)>=.86)})}accept(s){if(!this.allows(s))return false;this.exact.add(canonical(s));this.recent.push(this.tokens(s));if(this.recent.length>160)this.recent.shift();return true}}
const chatMemory=new Memory(),tipMemory=new Memory();
let running=true,elapsed=0,chatClock=0,nextChat=2,donationClock=0,nextGift=70,context=null,contextAge=0,burst=0,total=0,viewers=1284,follow=true,giftAge=0,activeGift=null,gifts=[],recentAmounts=[],sceneClock=0,sceneStep=0;
let manualUntil=0,cameraContext=false,giftGap=0,giftReactionAt=null,giftReactionAmount=0,giftReactionName='',viewerClock=0,lastTick=performance.now(),episode=[],replyName=null;
let media=null,wantedCamera=false,facing='user',cameraToken=0,cameraBusy=false;
function persona(){for(let i=0;i<300;i++){const a=pick(starts),b=pick(ends),n=Math.floor(Math.random()*100);const name=pick([a+'_'+b+(n<40?'':n),a+b[0].toUpperCase()+b.slice(1)+n,pick(['sam','jamie','alex','milo','jules','riley','kai','taylor','leo','drew','erin','max','ash','jordan','remy','charlie'])+'_'+b+(n<60?'':n),a+'.'+b+n,a+b+(n===0?'':n)]);if(!usedNames.has(name.toLowerCase())){usedNames.add(name.toLowerCase());return {name,initials:(name[0]+b[0]).toUpperCase(),color:pick(colors)}}}return null}
function add(text,person=persona(),gift=false,reply=null){if(!person)return;const chat=$('chat'),row=document.createElement('div'),avatar=document.createElement('span'),p=document.createElement('p'),name=document.createElement('strong');row.className='message'+(gift?' gift':'');avatar.className='avatar';avatar.style.background=person.color+'28';avatar.style.color=person.color;avatar.textContent=person.initials;if(reply){const link=document.createElement('span');link.className='reply';link.textContent='↳ '+reply;p.append(link)}name.style.color=person.color;name.textContent=person.name+' ';p.append(name,document.createTextNode(text));row.append(avatar,p);chat.append(row);while(chat.children.length>160)chat.firstChild.remove();if(follow)chat.scrollTop=chat.scrollHeight}
function activeScene(){return scenes[$('scenario').selectedIndex||1]}
function threads(key){return (library.threads[key]||[]).map((lines,i)=>({id:key+':'+i,lines}))}
function reaction(){if(!episode.length){const ambient=shuffle([...threads(activeScene()[0]),...threads('general')]),specific=context&&burst>0?shuffle(threads(context)):[];const thread=[...specific,...ambient].find(t=>!usedThreads.has(t.id)&&t.lines.some(x=>chatMemory.allows(x)));if(thread){usedThreads.add(thread.id);episode=cameraContext&&specific.includes(thread)?thread.lines.slice(0,Math.max(1,burst)):[...thread.lines];replyName=null}}let line;while(episode.length&&!line){const candidate=episode.shift();if(chatMemory.accept(candidate))line=candidate}if(!line)return;const person=persona();if(!person)return;add(line,person,false,replyName);replyName=episode.length?person.name:null;burst=Math.max(0,burst-1)}
function cue(event,fromCamera=false){if(!running||(fromCamera&&(!$('cameraReactions').checked||elapsed<manualUntil)))return;if(!fromCamera)manualUntil=elapsed+15;context=event;cameraContext=fromCamera;contextAge=0;burst=fromCamera?2:4;episode=[];replyName=null;reaction();scheduleChat();chatClock=0;$('contextLabel').textContent='Current cue: '+event;$('events').close()}
function scheduleChat(){const base=60/Number($('rate').value);nextChat=burst?1.5+Math.random()*2.2:episode.length?Math.max(1.1,base*(.5+Math.random()*.6)):Math.max(.8,base*(.65+Math.random()*.9));if(activeScene()[1]==='Study With Me'&&!context)nextChat*=1.5}
function scheduleGift(){const rate=Number($('giftRate').value);nextGift=rate?60/rate*(.75+Math.random()*.6):Infinity}
function gift(){if(!running||gifts.length>=12)return false;const person=persona();if(!person)return false;const low=Math.max(10,Math.min(900,Math.floor(Number($('minGift').value)||10))),high=Math.max(low,Math.min(900,Math.floor(Number($('maxGift').value)||900)));const choices=[[100,200,.8],[10,99,.17],[201,900,.03]].map(([a,b,w])=>{const lo=Math.max(low,a),hi=Math.min(high,b);return {values:lo<=hi?Array.from({length:hi-lo+1},(_,i)=>lo+i).filter(n=>!recentAmounts.includes(n)):[],weight:w}}).filter(x=>x.values.length);let amount=low;if(choices.length){let roll=Math.random()*choices.reduce((a,b)=>a+b.weight,0),pool=choices[choices.length-1].values;for(const choice of choices){roll-=choice.weight;if(roll<0){pool=choice.values;break}}const rounded=pool.filter(n=>n%5===0);amount=pick(rounded.length&&Math.random()<.85?rounded:pool)}recentAmounts.push(amount);if(recentAmounts.length>10)recentAmounts.shift();let note='';if(Math.random()>=.28){const lines=context?library.eventTips[context]||[]:[...(library.sceneTips[activeScene()[0]]||[]),...library.generalTips];note=shuffle(lines).find(x=>tipMemory.allows(x))||'';if(note)tipMemory.accept(note)}total+=amount;$('total').textContent='$'+total.toLocaleString('en-US');const g={amount,person,note,duration:Math.max(Number($('duration').value),Math.min(10,4+note.length*.035))+(amount>=500?1:0)};if(activeGift||gifts.length||giftGap>0)gifts.push(g);else showGift(g);add('✦ $'+amount.toLocaleString('en-US')+(note?' · '+note:' tip'),person,true);return true}
function showGift(g){activeGift=g;giftAge=0;if(Math.random()<(g.amount>=500?.95:.6)){giftReactionAt=elapsed+2+Math.random()*2;giftReactionAmount=g.amount;giftReactionName=g.person.name}$('giftAmount').textContent='$'+g.amount.toLocaleString('en-US');$('giftName').textContent=g.person.name;$('giftNote').textContent=g.note;$('giftAvatar').textContent=g.person.initials;$('giftAvatar').style.background=g.person.color+'28';$('giftAvatar').style.color=g.person.color;$('giftKind').textContent=g.amount>=500?'BIG SUPPORT':'JUST TIPPED';$('giftBanner').classList.toggle('large',g.amount>=500);$('giftProgress').style.width='100%';$('giftBanner').hidden=false}
function giftReaction(){const lines=giftReactionAmount>=500?["Wait, that's a big tip.","That was generous of you.","Huge support right there.","Okay, chat noticed that one.","A proper round of applause for that.","That's quite a contribution.","Big thank-you moment."]:["Kind of you.","Love seeing people support the channel.","A little applause from chat.","Nice gesture.","That's thoughtful.","Support coming through.","Cheers to that.","A tip from the quiet seats."];const line=shuffle(lines).find(x=>chatMemory.allows(x));if(line){chatMemory.accept(line);add(line,persona(),false,giftReactionName)}}
function clearCameraContext(){if(cameraContext){context=null;cameraContext=false;burst=0;episode=[];replyName=null;chatClock=0;scheduleChat()}}
function cameraMessage(title,detail){$('cameraTitle').textContent=title;$('cameraDetail').textContent=detail;$('cameraPlaceholder').style.display='flex';$('video').style.display='none'}
function stopCamera(){resetMotion();if(running)clearCameraContext();cameraToken++;if(media)media.getTracks().forEach(t=>t.stop());media=null;$('video').srcObject=null;cameraBusy=false;$('flip').disabled=true;$('cameraLabel').textContent='◉ Camera off';$('enableCamera').disabled=false;cameraMessage(running?'Your camera. Your stage.':'Stream paused',running?'Live on your screen. Nothing recorded or broadcast.':'Your camera and chat are on hold.');$('enableCamera').hidden=!running}
async function startCamera(){if(!running||cameraBusy)return;if(!navigator.mediaDevices?.getUserMedia){cameraMessage('Camera unavailable','Open this preview on localhost or HTTPS in a camera-capable browser.');return}stopCamera();wantedCamera=true;cameraBusy=true;const token=++cameraToken;$('enableCamera').disabled=true;cameraMessage('Starting camera…','Allow camera access in your browser. Microphone is not used.');try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:facing},width:{ideal:1280},height:{ideal:720}},audio:false});if(token!==cameraToken||!running||!wantedCamera){stream.getTracks().forEach(t=>t.stop());return}media=stream;const actual=stream.getVideoTracks()[0].getSettings().facingMode;const front=(actual??facing)==='user';$('video').srcObject=stream;$('video').classList.toggle('front',front);await $('video').play();if(token!==cameraToken)return;$('video').style.display='block';$('cameraPlaceholder').style.display='none';$('cameraLabel').textContent='◉ '+(actual==='environment'?'Rear camera':actual==='user'?'Front camera':'Camera live');$('flip').disabled=false;stream.getVideoTracks()[0].onended=()=>{if(media===stream){stopCamera();cameraMessage('Camera interrupted','Your camera was disconnected or access was revoked. Try enabling it again.')}}}catch(error){if(token!==cameraToken)return;stopCamera();cameraMessage(error.name==='NotAllowedError'?'Camera access is off':'Camera unavailable',error.name==='NotAllowedError'?'Allow camera access in your browser settings, then try again.':'Check your camera connection or close another app using it.')}finally{if(token===cameraToken){cameraBusy=false;$('enableCamera').disabled=false}}}
function pause(){running=!running;$('pause').textContent=running?'Ⅱ':'▷';$('pause').setAttribute('aria-label',running?'Pause stream and camera':'Resume stream and camera');$('status').textContent=running?'LIVE':'PAUSED';$('status').style.background=running?'#eb3348':'#62606b';['input','eventsButton','gift','cameraToggle'].forEach(id=>$(id).disabled=!running);$('compose').querySelector('button').disabled=!running;if(!running)stopCamera();else if(wantedCamera)startCamera();else stopCamera()}
scenes.forEach((s,i)=>{const option=document.createElement('option');option.textContent=s[0];$('scenario').append(option);const b=document.createElement('button');b.textContent=s[2]+' '+s[0];b.onclick=()=>{$('scenario').selectedIndex=i;changeScene()};$('sceneGrid').append(b)});
function changeScene(){context=null;cameraContext=false;burst=0;episode=[];replyName=null;sceneClock=0;sceneStep=0;$('category').textContent=activeScene()[1];[...$('sceneGrid').children].forEach((b,i)=>b.classList.toggle('selected',i===$('scenario').selectedIndex));$('contextLabel').textContent=activeScene()[0]+' · mixed voices';scheduleChat()}
cues.forEach(c=>{const b=document.createElement('button');b.textContent=c[0]+' '+c[1];b.onclick=()=>cue(c[1]);$('eventGrid').append(b)});
$('pause').onclick=pause;$('enableCamera').onclick=startCamera;$('cameraToggle').onclick=()=>{if(media||cameraBusy){wantedCamera=false;stopCamera()}else startCamera()};$('flip').onclick=()=>{facing=facing==='user'?'environment':'user';startCamera()};
$('eventsButton').onclick=()=>$('events').showModal();$('settingsButton').onclick=()=>$('settings').showModal();document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());$('gift').onclick=()=>{const ok=gift();$('giftFeedback').textContent=ok?'':'Gift queue is full.';if(ok)$('events').close()};
$('compose').onsubmit=e=>{e.preventDefault();if(!running)return;const text=$('input').value.trim();if(!text)return;add(text,{name:$('hostName').textContent+' [HOST]',initials:$('hostName').textContent.slice(0,2).toUpperCase(),color:'#bc94f4'});$('input').value='';const words=text.toLowerCase().match(/[\p{L}]+/gu)||[];const negative=/won['’]t|\b(not|never|didn|haven)\b/u.test(text.toLowerCase())||words.includes('не');if(!negative&&(words.includes('won')||words.includes('победа')))cue('Win');else if(words.includes('haha')||words.includes('хаха'))cue('Laugh');else if(words.includes('brb')||words.includes('перерыв'))cue('BRB')};
$('follow').onclick=()=>{follow=!follow;$('follow').setAttribute('aria-pressed',String(follow));$('follow').style.color=follow?'#a970ff':'#777';if(follow)$('chat').scrollTop=$('chat').scrollHeight};
$('rate').oninput=()=>{$('rateText').textContent=$('rate').value+' / min';scheduleChat()};$('giftRate').oninput=()=>{$('giftRateText').textContent=$('giftRate').value+' / min';donationClock=0;scheduleGift()};$('duration').oninput=()=>{$('durationText').textContent=$('duration').value+' seconds'};$('scenario').onchange=changeScene;
changeScene();for(let i=0;i<5;i++)reaction();scheduleChat();scheduleGift();
setInterval(()=>{const now=performance.now(),dt=Math.min(1,Math.max(0,(now-lastTick)/1000));lastTick=now;if(!running)return;elapsed+=dt;chatClock+=dt;donationClock+=dt;contextAge+=dt;sceneClock+=dt;viewerClock+=dt;if(context&&contextAge>=(cameraContext?9:20)){context=null;cameraContext=false;burst=0;episode=[];replyName=null;$('contextLabel').textContent='Choose a moment for chat to react to.'}giftGap=Math.max(0,giftGap-dt);if(activeGift){giftAge+=dt;$('giftProgress').style.width=Math.max(0,100*(1-giftAge/activeGift.duration))+'%';if(giftAge>=activeGift.duration){activeGift=null;giftGap=.8;$('giftBanner').hidden=true}}else if(gifts.length&&giftGap<=0)showGift(gifts.shift());if(giftReactionAt!==null&&elapsed>=giftReactionAt){giftReaction();giftReactionAt=null}if(chatClock>=nextChat){reaction();chatClock=0;scheduleChat()}if(Number($('giftRate').value)>0&&donationClock>=nextGift){gift();donationClock=0;scheduleGift()}if($('autoEvents').checked&&sceneClock>=50){cue((['Gaming','Challenges'].includes(activeScene()[1])?['Fail','Laugh','Win','Debate']:['Laugh','Debate','BRB','Back'])[sceneStep%4]);sceneStep++;sceneClock=0}const secs=Math.floor(elapsed);$('clock').textContent=[Math.floor(secs/3600),Math.floor(secs/60)%60,secs%60].map(x=>String(x).padStart(2,'0')).join(':');if(viewerClock>=3){viewerClock=0;viewers=Math.max(1,viewers+Math.trunc((1284-viewers)/15)+Math.floor(Math.random()*7)-3);$('viewers').textContent=viewers.toLocaleString('en-US')}},250);
function updateIdentity(){const name=$('channelName').value.trim().slice(0,24)||'nightshift',title=$('titleInput').value.trim().slice(0,80)||'Just one more minute';$('hostName').textContent=name;$('hostInitial').textContent=name[0].toUpperCase();$('streamTitle').textContent=title}
$('channelName').oninput=updateIdentity;$('titleInput').oninput=updateIdentity;$('editTitle').onclick=()=>{$('quickTitle').value=$('titleInput').value;$('quickName').value=$('channelName').value;$('titleEditor').showModal()};$('saveTitle').onclick=()=>{$('titleInput').value=$('quickTitle').value;$('channelName').value=$('quickName').value;updateIdentity();$('titleEditor').close()};
$('minGift').onchange=()=>{const value=Math.max(10,Math.min(900,Math.floor(Number($('minGift').value)||10)));$('minGift').value=value;$('maxGift').value=Math.max(value,Number($('maxGift').value)||900)};$('maxGift').onchange=()=>{const value=Math.max(10,Math.min(900,Math.floor(Number($('maxGift').value)||900)));$('maxGift').value=value;$('minGift').value=Math.min(value,Number($('minGift').value)||10)};
document.addEventListener('visibilitychange',()=>{if(document.hidden&&running)pause()});window.addEventListener('pagehide',()=>stopCamera());
// Browser preview supports motion cues only; native iOS additionally detects smiles/faces.
const motionCanvas=document.createElement('canvas');motionCanvas.width=24;motionCanvas.height=32;
const motionContext=motionCanvas.getContext('2d',{willReadFrequently:true});
let priorLuma=null,motionWarm=0,movingSince=null,quietSince=null,motionLatched=false,lastMotion=-1000;
function resetMotion(){priorLuma=null;motionWarm=0;movingSince=null;quietSince=null;motionLatched=false;lastMotion=-1000}
setInterval(()=>{if(!media||!running||!$('cameraReactions').checked||!motionContext||$('video').readyState<2)return;try{motionContext.drawImage($('video'),0,0,24,32);const pixels=motionContext.getImageData(0,0,24,32).data,luma=[];for(let i=0;i<pixels.length;i+=4)luma.push((pixels[i]*.299+pixels[i+1]*.587+pixels[i+2]*.114)/255);let amount=0;if(priorLuma){const delta=luma.map((n,i)=>n-priorLuma[i]),exposure=delta.reduce((a,b)=>a+b,0)/delta.length;amount=delta.reduce((sum,n)=>sum+Math.abs(n-exposure),0)/delta.length}priorLuma=luma;motionWarm+=.5;if(motionWarm<3)return;if(amount>.12){quietSince=null;if(movingSince===null)movingSince=elapsed;if(!motionLatched&&elapsed-movingSince>=1){motionLatched=true;if(elapsed-lastMotion>=70){lastMotion=elapsed;cue('Camera movement',true)}}}else{movingSince=null;if(quietSince===null)quietSince=elapsed;if(elapsed-quietSince>=3)motionLatched=false}}catch{resetMotion()}},500);
$('cameraReactions').onchange=()=>{resetMotion();if(!$('cameraReactions').checked)clearCameraContext()};
